In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

In [4]:
imigration_data = pd.read_csv(r'C:\Users\Jp Lima\Desktop\alura_course\datasets\canadian_immegration_data.csv')
imigration_data.head()

,Country,Continent,Region,DevName,1980,1981,1982,1983,1984,1985,...,2005,2006,2007,2008,2009,2010,2011,2012,2013,Total
0,Afghanistan,Asia,Southern Asia,Developing regions,16,39,39,47,71,340,...,3436,3009,2652,2111,1746,1758,2203,2635,2004,58639
1,Albania,Europe,Southern Europe,Developed regions,1,0,0,0,0,0,...,1223,856,702,560,716,561,539,620,603,15699
2,Algeria,Africa,Northern Africa,Developing regions,80,67,71,69,63,44,...,3626,4807,3623,4005,5393,4752,4325,3774,4331,69439
3,American Samoa,Oceania,Polynesia,Developing regions,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,0,6
4,Andorra,Europe,Southern Europe,Developed regions,0,0,0,0,0,0,...,0,1,1,0,0,0,0,1,1,15

In [5]:
imigration_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 39 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Country    195 non-null    object
 1   Continent  195 non-null    object
 2   Region     195 non-null    object
 3   DevName    195 non-null    object
 4   1980       195 non-null    int64
 5   1981       195 non-null    int64
 6   1982       195 non-null    int64
 7   1983       195 non-null    int64
 8   1984       195 non-null    int64
 9   1985       195 non-null    int64
 10  1986       195 non-null    int64
 11  1987       195 non-null    int64
 12  1988       195 non-null    int64
 13  1989       195 non-null    int64
 14  1990       195 non-null    int64
 15  1991       195 non-null    int64
 16  1992       195 non-null    int64
 17  1993       195 non-null    int64
 18  1994       195 non-null    int64
 19  1995       195 non-null    int64
 20  1996       195 non-null    int64
 21  1997       195 non-null    int64
 22  1998       195 non-null    int64
 23  1999       195 non-null    int64
 24  2000       195 non-null    int64
 25  2001       195 non-null    int64
 26  2002       195 non-null    int64
 27  2003       195 non-null    int64
 28  2004       195 non-null    int64
 29  2005       195 non-null    int64
 30  2006       195 non-null    int64
 31  2007       195 non-null    int64
 32  2008       195 non-null    int64
 33  2009       195 non-null    int64
 34  2010       195 non-null    int64
 35  2011       195 non-null    int64
 36  2012       195 non-null    int64
 37  2013       195 non-null    int64
 38  Total      195 non-null    int64
dtypes: int64(35), object(4)
memory usage: 59.5+ KB

In [7]:
imigration_data.set_index('Country', inplace=True)

In [8]:
anos = list(map(str, range(1980, 2014)))

In [11]:
brasil = imigration_data.loc['Brazil', anos]
brasil

1980     211
1981     220
1982     192
1983     139
1984     145
1985     130
1986     205
1987     244
1988     394
1989     650
1990     650
1991     877
1992    1066
1993     866
1994     566
1995     572
1996     586
1997     591
1998     531
1999     626
2000     845
2001     847
2002     745
2003     839
2004     917
2005     969
2006    1181
2007    1746
2008    2138
2009    2509
2010    2598
2011    1508
2012    1642
2013    1714
Name: Brazil, dtype: object

In [12]:
brasil_dict = {'ano': brasil.index.tolist(), 'imigrantes': brasil.values.tolist()}
brasil_data = pd.DataFrame(brasil_dict)

In [13]:
brasil_data

     ano  imigrantes
0   1980         211
1   1981         220
2   1982         192
3   1983         139
4   1984         145
5   1985         130
6   1986         205
7   1987         244
8   1988         394
9   1989         650
10  1990         650
11  1991         877
12  1992        1066
13  1993         866
14  1994         566
15  1995         572
16  1996         586
17  1997         591
18  1998         531
19  1999         626
20  2000         845
21  2001         847
22  2002         745
23  2003         839
24  2004         917
25  2005         969
26  2006        1181
27  2007        1746
28  2008        2138
29  2009        2509
30  2010        2598
31  2011        1508
32  2012        1642
33  2013        1714